package gogen

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Lumos-Labs-HQ/flash/internal/gencommon"
	"github.com/Lumos-Labs-HQ/flash/internal/parser"
)

// generateQueriesIncremental generates queries with incremental support  
func (g *Generator) generateQueriesIncremental(queries []*parser.Query, fullRegen bool) error {
	queryGroups := make(map[string][]*parser.Query)
	for _, query := range queries {
		sourceFile := query.SourceFile
		if sourceFile == "" {
			sourceFile = "queries"
		}
		queryGroups[sourceFile] = append(queryGroups[sourceFile], query)
	}

	usedNames := make(map[string]int)

	for sourceFile, fileQueries := range queryGroups {
		queryFile := filepath.Join(g.Config.Queries, sourceFile+".sql")
		currentHash, _ := gencommon.ComputeFileChecksum(queryFile)
		
		if !gencommon.ShouldRegenerateFile(g.cache, queryFile, currentHash, fullRegen) {
			gencommon.PrintSkipMessage(sourceFile, ".go")
			continue
		}

		gencommon.PrintGenerateMessage(sourceFile, ".go")
		
		estimatedSize := 200 + (len(fileQueries) * 400) + (len(g.schema.Tables) * 200)
		var code strings.Builder
		code.Grow(estimatedSize)

		code.WriteString("// Code generated by FlashORM. DO NOT EDIT.\n\n")
		code.WriteString("package flash_gen\n\n")

		needsTime, needsSQL := false, false
		for _, query := range fileQueries {
			for _, col := range query.Columns {
				colType := g.mapColumnTypeToGo(col.Type, col.Nullable)
				if strings.Contains(colType, "time.Time") {
					needsTime = true
				}
				if strings.Contains(colType, "sql.Null") {
					needsSQL = true
				}
			}
			if strings.ToLower(query.Cmd) == ":one" {
				needsSQL = true
			}
		}

		imports := []string{}
		if needsSQL {
			imports = append(imports, "\"database/sql\"")
		}
		if needsTime {
			imports = append(imports, "\"time\"")
		}

		if len(imports) > 0 {
			code.WriteString("import (\n")
			for _, imp := range imports {
				code.WriteString(fmt.Sprintf("\t%s\n", imp))
			}
			code.WriteString(")\n\n")
		}

		for _, query := range fileQueries {
			if err := g.generateQueryMethod(&code, query); err != nil {
				return err
			}
		}

		baseName := strings.TrimSuffix(sourceFile, ".sql")
		outputFile := baseName + ".go"

		if count, exists := usedNames[baseName]; exists {
			usedNames[baseName] = count + 1
			outputFile = fmt.Sprintf("%s_%d.go", baseName, count+1)
		} else {
			usedNames[baseName] = 1
		}

		queriesPath := filepath.Join("flash_gen", outputFile)
		if err := os.WriteFile(queriesPath, []byte(code.String()), 0644); err != nil {
			return err
		}

		tableDeps := gencommon.ExtractTableDependencies(fileQueries)
		gencommon.UpdateCacheForFile(g.cache, queryFile, currentHash, tableDeps, queriesPath)
	}

	return nil
}
