// Code generated by Graft. DO NOT EDIT.
const { Queries: SpacicalQueries } = require('./spacical');
const { Queries: UsersQueries } = require('./users');

// Combine all query classes into one
class Queries {
  constructor(db) {
    this.db = db;
    const _spacical = new SpacicalQueries(db);
    Object.getOwnPropertyNames(Object.getPrototypeOf(_spacical)).forEach(name => {
      if (name !== 'constructor' && typeof _spacical[name] === 'function') {
        this[name] = _spacical[name].bind(_spacical);
      }
    });

    const _users = new UsersQueries(db);
    Object.getOwnPropertyNames(Object.getPrototypeOf(_users)).forEach(name => {
      if (name !== 'constructor' && typeof _users[name] === 'function') {
        this[name] = _users[name].bind(_users);
      }
    });
  }
}

/**
 * Create a new database client
 * @param {Object} db - Database connection (pg.Pool, mysql2.Pool, or better-sqlite3 instance)
 * @returns {Queries}
 */
function New(db) {
  return new Queries(db);
}

module.exports = { New, Queries };
