# Code generated by Graft. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional
from datetime import datetime

@dataclass
class Users:
    id: int
    name: str
    email: str
    created_at: datetime
    updated_at: datetime

