# Code generated by Graft. DO NOT EDIT.

from typing import Optional, List, Any

class Queries:
    def __init__(self, db):
        self.db = db
        self._stmts = {}

    async def get_user(self, id: int) -> Optional[dict]:
        stmt = """SELECT id, name, email, created_at, updated_at FROM users WHERE id = $1 LIMIT 1;"""
        result = await self.db.fetch(stmt, id)
        return dict(result[0]) if result else None

    async def create_user(self, name: str, email: str) -> Optional[dict]:
        stmt = """INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id, name, email, created_at, updated_at;"""
        result = await self.db.fetch(stmt, name, email)
        return dict(result[0]) if result else None

