// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package graft

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int32
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Comment struct {
	ID        int32
	PostID    int32
	UserID    int32
	Content   string
	CreatedAt pgtype.Timestamptz
}

type Post struct {
	ID         int32
	UserID     int32
	CategoryID int32
	Title      string
	Content    string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type User struct {
	ID        int32
	Name      string
	Address   pgtype.Text
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
