// Code generated by Graft. DO NOT EDIT.

package graft_gen

import (
	"database/sql"
	"time"
)

type PostStatus string

const (
	PostStatusDraft PostStatus = "draft"
	PostStatusPublished PostStatus = "published"
	PostStatusArchived PostStatus = "archived"
)

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleModerator UserRole = "moderator"
	UserRoleUser UserRole = "user"
	UserRoleGuest UserRole = "guest"
)

type Users struct {
	Id int64 `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
	Address sql.NullString `json:"address" db:"address"`
	Isadmin bool `json:"isadmin" db:"isadmin"`
	Email string `json:"email" db:"email"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	Role UserRole `json:"role" db:"role"`
}

type Posts struct {
	Id int64 `json:"id" db:"id"`
	UserId int64 `json:"user_id" db:"user_id"`
	CategoryId int64 `json:"category_id" db:"category_id"`
	Title string `json:"title" db:"title"`
	Content string `json:"content" db:"content"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
	UpdatedAt time.Time `json:"updated_at" db:"updated_at"`
	Status PostStatus `json:"status" db:"status"`
}

type Categories struct {
	Id int64 `json:"id" db:"id"`
	Name string `json:"name" db:"name"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

type Comments struct {
	Id int64 `json:"id" db:"id"`
	PostId int64 `json:"post_id" db:"post_id"`
	UserId int64 `json:"user_id" db:"user_id"`
	Content string `json:"content" db:"content"`
	CreatedAt time.Time `json:"created_at" db:"created_at"`
}

