// Code generated by Graft. DO NOT EDIT.

package graft_gen

import (
	"database/sql"
)

func (q *Queries) Checkisadmin(id int64) (bool, error) {
	const query = `SELECT isadmin FROM users WHERE id = $1 LIMIT 1;`
	args := []interface{}{id}

	var result bool
	rows, err := q.db.Query(query, args...)
	if err != nil {
		return result, err
	}
	defer rows.Close()
	if !rows.Next() {
		if err := rows.Err(); err != nil {
			return result, err
		}
		return result, sql.ErrNoRows
	}
	err = rows.Scan(&result)
	return result, err
}

