// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package graft

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateCategory(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, name)
	var i Category
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (post_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, post_id, user_id, content, created_at
`

type CreateCommentParams struct {
	PostID  int32
	UserID  int32
	Content string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.PostID, arg.UserID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (user_id, category_id, title, content)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, category_id, title, content, created_at, updated_at, status
`

type CreatePostParams struct {
	UserID     int32
	CategoryID int32
	Title      string
	Content    string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.UserID,
		arg.CategoryID,
		arg.Title,
		arg.Content,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email)
VALUES ($1, $2)
RETURNING id, name, address, isadmin, email, created_at, updated_at, role
`

type CreateUserParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Isadmin,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getPostDetailsWithAllRelations = `-- name: GetPostDetailsWithAllRelations :one
SELECT 
    p.id,
    p.title,
    p.content,
    p.status,
    p.created_at,
    p.updated_at,
    u.id as author_id,
    u.name as author_name,
    u.email as author_email,
    u.role as author_role,
    u.isadmin as author_is_admin,
    cat.id as category_id,
    cat.name as category_name,
    COUNT(DISTINCT c.id) as comment_count,
    COUNT(DISTINCT c.user_id) as unique_commenters,
    STRING_AGG(DISTINCT c.content, ' | ' ORDER BY c.content) as all_comments,
    ARRAY_AGG(DISTINCT cu.name ORDER BY cu.name) as commenter_names,
    MAX(c.created_at) as last_comment_date,
    LENGTH(p.content) as content_length,
    EXTRACT(EPOCH FROM (NOW() - p.created_at)) / 3600 as hours_since_created
FROM posts p
INNER JOIN users u ON p.user_id = u.id
INNER JOIN categories cat ON p.category_id = cat.id
LEFT JOIN comments c ON p.id = c.post_id
LEFT JOIN users cu ON c.user_id = cu.id
WHERE p.id = $1
GROUP BY 
    p.id, p.title, p.content, p.status, p.created_at, p.updated_at,
    u.id, u.name, u.email, u.role, u.isadmin,
    cat.id, cat.name
`

type GetPostDetailsWithAllRelationsRow struct {
	ID                int32
	Title             string
	Content           string
	Status            PostStatus
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AuthorID          int32
	AuthorName        string
	AuthorEmail       string
	AuthorRole        UserRole
	AuthorIsAdmin     bool
	CategoryID        int32
	CategoryName      string
	CommentCount      int64
	UniqueCommenters  int64
	AllComments       []byte
	CommenterNames    interface{}
	LastCommentDate   interface{}
	ContentLength     float64
	HoursSinceCreated int32
}

func (q *Queries) GetPostDetailsWithAllRelations(ctx context.Context, id int32) (GetPostDetailsWithAllRelationsRow, error) {
	row := q.db.QueryRow(ctx, getPostDetailsWithAllRelations, id)
	var i GetPostDetailsWithAllRelationsRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.AuthorRole,
		&i.AuthorIsAdmin,
		&i.CategoryID,
		&i.CategoryName,
		&i.CommentCount,
		&i.UniqueCommenters,
		&i.AllComments,
		&i.CommenterNames,
		&i.LastCommentDate,
		&i.ContentLength,
		&i.HoursSinceCreated,
	)
	return i, err
}

const getPostWithComments = `-- name: GetPostWithComments :many
SELECT p.id AS post_id, p.title, p.content, u.name AS author, c.content AS comment_text, cu.name AS commenter
FROM posts p
JOIN users u ON p.user_id = u.id
LEFT JOIN comments c ON p.id = c.post_id
LEFT JOIN users cu ON c.user_id = cu.id
WHERE p.id = $1
`

type GetPostWithCommentsRow struct {
	PostID      int32
	Title       string
	Content     string
	Author      string
	CommentText pgtype.Text
	Commenter   pgtype.Text
}

func (q *Queries) GetPostWithComments(ctx context.Context, id int32) ([]GetPostWithCommentsRow, error) {
	rows, err := q.db.Query(ctx, getPostWithComments, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostWithCommentsRow
	for rows.Next() {
		var i GetPostWithCommentsRow
		if err := rows.Scan(
			&i.PostID,
			&i.Title,
			&i.Content,
			&i.Author,
			&i.CommentText,
			&i.Commenter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, name, address, isadmin, email, created_at, updated_at, role FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Isadmin,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}
