// Code generated by Graft. DO NOT EDIT.
const { Queries } = require('./queries');

/**
 * Create a new database client
 * @param {Object} db - Database connection (pg.Pool, mysql2.Pool, or better-sqlite3 instance)
 * @returns {Queries}
 */
function New(db) {
  return new Queries(db);
}

module.exports = { New, Queries };
