// Code generated by Graft. DO NOT EDIT.

export interface Users {
  id: number | null;
  name: string;
  address: string | null;
  isadmin: boolean;
  email: string;
  created_at: Date;
  updated_at: Date;
}

export interface Posts {
  id: number | null;
  user_id: number;
  category_id: number;
  title: string;
  content: string;
  created_at: Date;
  updated_at: Date;
}

export interface Categories {
  id: number | null;
  name: string;
  created_at: Date;
}

export interface Comments {
  id: number | null;
  post_id: number;
  user_id: number;
  content: string;
  created_at: Date;
}

export interface GetActiveUsersWithStatsResult {
  id: number | null;
  name: string;
  email: string;
  isadmin: boolean;
  total_posts: number;
  total_comments: number;
  last_post_date: Date;
}

export interface GetTopActiveUsersResult {
  id: number | null;
  name: string;
  email: string;
  total_posts: number;
  total_comments: number;
}

export interface GetMostCommentedPostsResult {
  id: number | null;
  title: string;
  author: string;
  comment_count: number;
}

export interface GetUsersCreatedBetweenResult {
  id: number | null;
  name: string;
  email: string;
  created_at: Date;
}

export interface GetPostsByCategoryResult {
  id: number | null;
  title: string;
  content: string;
  author_name: string;
  created_at: Date;
}

export class Queries {
  constructor(db: any);

  isadminUser(id: number): Promise<boolean | null>;
  getUserEmail(id: number): Promise<string | null>;
  getUserName(id: number): Promise<string | null>;
  getUserByEmail(email: string): Promise<Users | null>;
  getActiveUsersWithStats(): Promise<GetActiveUsersWithStatsResult[]>;
  getTopActiveUsers(): Promise<GetTopActiveUsersResult[]>;
  createUser(name: string, email: string, address: string, isadmin: boolean): Promise<number>;
  createPost(user_id: number, category_id: number, title: string, content: string): Promise<number>;
  createComment(post_id: number, user_id: number, content: string): Promise<number>;
  createCategory(user_id: number): Promise<number>;
  getAveragePostsPerUser(): Promise<number | null>;
  getMostCommentedPosts(limit: number): Promise<GetMostCommentedPostsResult[]>;
  checkUserExists(email: string): Promise<boolean | null>;
  getUsersCreatedBetween(created_at_start: Date, created_at_end: Date): Promise<GetUsersCreatedBetweenResult[]>;
  updateUserAdminStatus(id: number, isadmin: boolean): Promise<number>;
  deleteInactiveUsers(created_at: Date): Promise<number>;
  getPostsByCategory(category_id: number): Promise<GetPostsByCategoryResult[]>;
}

export function New(db: any): Queries;
