// Code generated by Graft. DO NOT EDIT.

/**
 * @typedef {Object} Users
 * @property {number|null} id
 * @property {string} name
 * @property {string|null} address
 * @property {boolean} isadmin
 * @property {string} email
 * @property {Date} created_at
 * @property {Date} updated_at
 */

/**
 * @typedef {Object} Posts
 * @property {number|null} id
 * @property {number} user_id
 * @property {number} category_id
 * @property {string} title
 * @property {string} content
 * @property {Date} created_at
 * @property {Date} updated_at
 */

/**
 * @typedef {Object} Categories
 * @property {number|null} id
 * @property {string} name
 * @property {Date} created_at
 */

/**
 * @typedef {Object} Comments
 * @property {number|null} id
 * @property {number} post_id
 * @property {number} user_id
 * @property {string} content
 * @property {Date} created_at
 */

module.exports = {};
