// Code generated by FlashORM. DO NOT EDIT.

export interface Users {
  id: number;
  name: string;
  address: string | null;
  isadmin: boolean;
  email: string;
  created_at: Date;
  updated_at: Date;
  role: 'admin' | 'moderator' | 'user' | 'guest';
}

export interface Categories {
  id: number;
  name: string;
  created_at: Date;
}

export interface Comments {
  id: number;
  post_id: number;
  user_id: number;
  content: string;
  created_at: Date;
}

export interface Posts {
  id: number;
  user_id: number;
  category_id: number;
  title: string;
  content: string;
  created_at: Date;
  updated_at: Date;
  status: 'draft' | 'published' | 'archived';
}

export interface GetPostWithCommentsResult {
  post_id: number;
  title: string;
  content: string;
  author: string;
  comment_text: string;
  commenter: string;
}

export interface GetPostDetailsWithAllRelationsResult {
  id: number;
  title: string;
  content: string;
  status: 'draft' | 'published' | 'archived';
  created_at: Date;
  updated_at: Date;
  author_id: number;
  author_name: string;
  author_email: string;
  author_role: string;
  author_is_admin: boolean;
  category_id: number;
  category_name: string;
  comment_count: number;
  unique_commenters: string;
  all_comments: string;
  commenter_names: string;
  last_comment_date: Date;
  content_length: string;
  hours_since_created: string;
}

export class Queries {
  constructor(db: any);

  createUser(name: string, email: string): Promise<Users | null>;
  getUser(id: number): Promise<Users | null>;
  getUserByEmail(email: string): Promise<Users | null>;
  createCategory(name: string): Promise<Categories | null>;
  createPost(user_id: number, category_id: number, title: string, content: string): Promise<Posts | null>;
  createComment(post_id: number, user_id: number, content: string): Promise<Comments | null>;
  getPostWithComments(id: number): Promise<GetPostWithCommentsResult[]>;
  getPostDetailsWithAllRelations(id: number): Promise<GetPostDetailsWithAllRelationsResult | null>;
}

export function New(db: any): Queries;
