# Code generated by FlashORM. DO NOT EDIT.
from .users import Queries


def new(db):
    """
    Create a new database client.
    
    Args:
        db: Database connection (asyncpg.Pool, aiomysql.Pool, or aiosqlite connection)
    
    Returns:
        Queries: An instance of the Queries class
    """
    return Queries(db)
