# Code generated by FlashORM. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional
from datetime import datetime

@dataclass
class Users:
    id: int
    name: str
    address: Optional[str]
    isadmin: bool
    email: str
    created_at: datetime
    updated_at: datetime
    role: str

@dataclass
class Categories:
    id: int
    name: str
    created_at: datetime

@dataclass
class Posts:
    id: int
    user_id: int
    category_id: int
    title: str
    content: str
    created_at: datetime
    updated_at: datetime
    status: str

@dataclass
class Comments:
    id: int
    post_id: int
    user_id: int
    content: str
    created_at: datetime

