# Code generated by FlashORM. DO NOT EDIT.

from dataclasses import dataclass
from typing import Optional, List, Any, Literal
from datetime import datetime
from decimal import Decimal

@dataclass
class GetuserRow:
    id: int
    name: str
    email: str
    created_at: datetime
    updated_at: datetime

    @classmethod
    def _make_fast(cls, record):
        """Optimized factory: 2-3x faster than **dict(record)"""
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['created_at'],
            record['updated_at']
        )

@dataclass
class CreateuserRow:
    id: int
    name: str
    email: str
    created_at: datetime
    updated_at: datetime

    @classmethod
    def _make_fast(cls, record):
        """Optimized factory: 2-3x faster than **dict(record)"""
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['created_at'],
            record['updated_at']
        )

@dataclass
class ListusersRow:
    id: int
    name: str
    email: str
    created_at: datetime
    updated_at: datetime

    @classmethod
    def _make_fast(cls, record):
        """Optimized factory: 2-3x faster than **dict(record)"""
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['created_at'],
            record['updated_at']
        )

@dataclass
class UpdateuserRow:
    id: int
    name: str
    email: str
    created_at: datetime
    updated_at: datetime

    @classmethod
    def _make_fast(cls, record):
        """Optimized factory: 2-3x faster than **dict(record)"""
        return cls(
            record['id'],
            record['name'],
            record['email'],
            record['created_at'],
            record['updated_at']
        )

class Queries:
    def __init__(self, db):
        self.db = db
        self._stmts = {}

    async def get_user(self, id: int) -> Optional[GetuserRow]:
        stmt = """SELECT id, name, email, created_at, updated_at FROM users WHERE id = $1 LIMIT 1;"""
        result = await self.db.fetch(stmt, id)
        return GetuserRow._make_fast(result[0]) if result else None

    async def create_user(self, name: str, email: str) -> Optional[CreateuserRow]:
        stmt = """INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id, name, email, created_at, updated_at;"""
        result = await self.db.fetch(stmt, name, email)
        return CreateuserRow._make_fast(result[0]) if result else None

    async def list_users(self, ) -> List[ListusersRow]:
        stmt = """SELECT id, name, email, created_at, updated_at FROM users ORDER BY created_at DESC;"""
        result = await self.db.fetch(stmt)
        return [ListusersRow._make_fast(row) for row in result]

    async def update_user(self, id: int, name: str, email: str) -> Optional[UpdateuserRow]:
        stmt = """UPDATE users SET name = $2, email = $3, updated_at = NOW() WHERE id = $1 RETURNING id, name, email, created_at, updated_at;"""
        result = await self.db.fetch(stmt, id, name, email)
        return UpdateuserRow._make_fast(result[0]) if result else None

    async def delete_user(self, id: int) -> int:
        stmt = """DELETE FROM users WHERE id = $1;"""
        await self.db.execute(stmt, id)
        return 1

